/* Generated By:JavaCC: Do not edit this line. OILParserConstants.java */
package com.jkenergy.rtos.config.parser;

public interface OILParserConstants {

  int EOF = 0;
  int OS = 7;
  int TASK = 8;
  int COUNTER = 9;
  int ALARM = 10;
  int RESOURCE = 11;
  int EVENT = 12;
  int ISR = 13;
  int MESSAGE = 14;
  int COM = 15;
  int APPMODE = 16;
  int NM = 17;
  int IPDU = 18;
  int APPLICATION = 19;
  int SCHEDULETABLE = 20;
  int OS_TYPE = 21;
  int TASK_TYPE = 22;
  int COUNTER_TYPE = 23;
  int ALARM_TYPE = 24;
  int RESOURCE_TYPE = 25;
  int EVENT_TYPE = 26;
  int ISR_TYPE = 27;
  int MESSAGE_TYPE = 28;
  int COM_TYPE = 29;
  int APPMODE_TYPE = 30;
  int NM_TYPE = 31;
  int IPDU_TYPE = 32;
  int APPLICATION_TYPE = 33;
  int SCHEDULETABLE_TYPE = 34;
  int NO_DEFAULT = 35;
  int AUTO = 36;
  int WITH_AUTO = 37;
  int IMPLEMENTATION = 38;
  int OIL_VERSION = 39;
  int CPU = 40;
  int TRUE = 41;
  int FALSE = 42;
  int UINT32 = 43;
  int INT32 = 44;
  int UINT64 = 45;
  int INT64 = 46;
  int FLOAT = 47;
  int ENUM = 48;
  int STRING = 49;
  int BOOLEAN = 50;
  int NAME = 51;
  int LETTER = 52;
  int DIGIT = 53;
  int STRING_LITERAL = 54;
  int SEARCH_FILENAME = 55;
  int NUMBER_LITERAL = 56;
  int DECIMAL_NUMBER = 57;
  int HEX_NUMBER = 58;
  int FLOAT_LITERAL = 59;
  int EXPONENT = 60;
  int COMMA = 61;
  int COLON = 62;
  int SEMICOLON = 63;
  int EQUALS = 64;
  int LBRACKET = 65;
  int RBRACKET = 66;
  int LBRACE = 67;
  int RBRACE = 68;
  int RANGE = 69;
  int UNEXPECTED_CHAR = 70;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "\"OS\"",
    "\"TASK\"",
    "\"COUNTER\"",
    "\"ALARM\"",
    "\"RESOURCE\"",
    "\"EVENT\"",
    "\"ISR\"",
    "\"MESSAGE\"",
    "\"COM\"",
    "\"APPMODE\"",
    "\"NM\"",
    "\"IPDU\"",
    "\"APPLICATION\"",
    "\"SCHEDULETABLE\"",
    "\"OS_TYPE\"",
    "\"TASK_TYPE\"",
    "\"COUNTER_TYPE\"",
    "\"ALARM_TYPE\"",
    "\"RESOURCE_TYPE\"",
    "\"EVENT_TYPE\"",
    "\"ISR_TYPE\"",
    "\"MESSAGE_TYPE\"",
    "\"COM_TYPE\"",
    "\"APPMODE_TYPE\"",
    "\"NM_TYPE\"",
    "\"IPDU_TYPE\"",
    "\"APPLICATION_TYPE\"",
    "\"SCHEDULETABLE_TYPE\"",
    "\"NO_DEFAULT\"",
    "\"AUTO\"",
    "\"WITH_AUTO\"",
    "\"IMPLEMENTATION\"",
    "\"OIL_VERSION\"",
    "\"CPU\"",
    "\"TRUE\"",
    "\"FALSE\"",
    "\"UINT32\"",
    "\"INT32\"",
    "\"UINT64\"",
    "\"INT64\"",
    "\"FLOAT\"",
    "\"ENUM\"",
    "\"STRING\"",
    "\"BOOLEAN\"",
    "<NAME>",
    "<LETTER>",
    "<DIGIT>",
    "<STRING_LITERAL>",
    "<SEARCH_FILENAME>",
    "<NUMBER_LITERAL>",
    "<DECIMAL_NUMBER>",
    "<HEX_NUMBER>",
    "<FLOAT_LITERAL>",
    "<EXPONENT>",
    "\",\"",
    "\":\"",
    "\";\"",
    "\"=\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\"..\"",
    "<UNEXPECTED_CHAR>",
  };

}
