/* Copyright (C) 2004, 2005, 2006 JK Energy Ltd.
 * 
 * $LastChangedDate: 2008-01-09 07:20:24 +0000 (Wed, 09 Jan 2008) $
 * $LastChangedRevision: 516 $
 * $LastChangedBy: kentindell $
 * $HeadURL: http://10.211.55.3/svn/repos/ertcs/rtos/trunk/embedded/src/OS/dsPIC/drivers/tmrgen.c $
 * 
 * This file contains an example piece of autogenerated code (gen.c) for the timer[2/3] drivers. These drivers
 * are compiled up and included in the application build.
 */
#include <osgen.h>

/***********PLACEHOLDER FOR AUTOGENERATED CODE***************/

#define T2_OCxR							OC8R
#define T2_OCxCON						OC8CON
#define T2_OCxCON_INIT					(0x3456U)		/* @todo made up rubbish replaced by codegen */
#define T2CON_INIT						(0x1234U)		/* @todo made up rubbish replaced by codegen */
#define T2_OCx_INTERRUPT_DISMISS		OC8_INTERRUPT_DISMISS
#define T2_OCx_INTERRUPT_SET_PENDING	OC8_INTERRUPT_SET_PENDING
#define T2_OCx_INTERRUPT_DISABLE		OC8_INTERRUPT_DISABLE
#define T2_OCx_INTERRUPT_ENABLE			OC8_INTERRUPT_ENABLE
#define T2_OCxR							OC8R
#define T2_OCxCON						OC8CON

#define T3_OCxR							OC7R
#define T3_OCxCON						OC7CON
#define T3_OCxCON_INIT					(0x3456U)		/* @todo made up rubbish replaced by codegen */
#define T3CON_INIT						(0x1234U)		/* @todo made up rubbish replaced by codegen */
#define T3_OCx_INTERRUPT_DISMISS		OC7_INTERRUPT_DISMISS
#define T3_OCx_INTERRUPT_SET_PENDING	OC7_INTERRUPT_SET_PENDING
#define T3_OCx_INTERRUPT_DISABLE		OC7_INTERRUPT_DISABLE
#define T3_OCx_INTERRUPT_ENABLE			OC7_INTERRUPT_ENABLE
#define T3_OCxR							OC7R
#define T3_OCxCON						OC7CON

#define TIMER2
#define TIMER3

#include "timer23.h"



///////////////////THIS IS THE TEMPLATE FOR ALL AUTOGENERATED CODE FOR TIMERS (PLATFORM-INDEPENDENT CODE)//////////////
ISR(os_oc8)
{
	ExpireCounter(0);			/* Placeholder value; the counter is known at configuration build time */
}

ISR(os_oc7)
{
	ExpireCounter(0);			/* Placeholder value; the counter is known at configuration build time */
}
