# Build all tests

all:
	cd Test1 && make -f build.mf
	cd Test2 && make -f build.mf
	cd Test3 && make -f build.mf
	cd Test4 && make -f build.mf
	cd Test4a && make -f build.mf
	cd Test5 && make -f build.mf
	cd Test5a && make -f build.mf
	cd Test5b && make -f build.mf
	cd Test6 && make -f build.mf
	cd Test7 && make -f build.mf
	cd Test8 && make -f build.mf
	cd Test9 && make -f build.mf
			
clean:
	cd Test1 && make -f build.mf clean
	cd Test2 && make -f build.mf clean
	cd Test3 && make -f build.mf clean
	cd Test4 && make -f build.mf clean
	cd Test4a && make -f build.mf clean
	cd Test5 && make -f build.mf clean
	cd Test5a && make -f build.mf clean
	cd Test5b && make -f build.mf clean
	cd Test6 && make -f build.mf clean
	cd Test7 && make -f build.mf clean
	cd Test8 && make -f build.mf clean
	cd Test9 && make -f build.mf clean
		